sudo: required
services:
  - docker

before_install:
  - docker build -t hejjzaen/docker-flow -f Dockerfile.dev .

script:
  - docker run hejjzaen/docker-flow npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "doker-flow"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-857311930"
  bucket_path: "docker-flow"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
